### ISSUE TITLE
Remember Tilt

### ISSUE THREAD

**Issue by Castro3halo** [NullNameException/camera-points#10]
Camera remembers zoom and angle, is it possible for it to remember tilt or manually enter in a tilt value for it to snap to.

**Comment by NullNameException** [comment]
I did ask in the discord server but sadly "Presets for Camera yaw/pitch/position" is still a rejected feature.
https://github.com/runelite/runelite/wiki/Rejected-or-Rolled-Back-Features

However I did upate the plugin to now correctly save and load the compass direction you chose.
But, as a click on the compass would, this changes the tilt.

**Comment by notheowner** [comment]
> 

Clicking on the compass doesn't necessarily reset the tilt anymore since the default Camera plugin has an option "Preserve pitch on compass look" so clicking the compass just resets the direction.
Thanks for the response nonetheless.

**Comment by NullNameException** [comment]
Very interesting, I did not know about this.
I just tested this and was surprised to find out it already works!
Enabling the "Preserve pitch on compass look" option in the default camera plugin will also apply to compass directions you load using this plugin.
