### ISSUE TITLE
Camera Direction Not Saving

### ISSUE THREAD

**Issue by HiImSevan** [NullNameException/camera-points#11]
After I make a camera point, the zoom in amount seems to work fine, but the direction (north, south, east, west) doesnt save. The first couple times pressing the hotkey for the camera point it will remember, but a minute later the directions wont work, then when i go to check the side-bar app, the camera points are back to "unchanged".

**Comment by NullNameException** [comment]
Turns out the direction was saved correctly but it was never loaded when loading the camera points. So once this is fixed, they should all appear like they have been saved previously.
Thanks for letting me know!
