### ISSUE TITLE
Compass direction dropdown applies incorrect compass direction

### ISSUE THREAD

**Issue by trentet** [NullNameException/camera-points#5]
For a given Camera Point entry, some compass directions that become applied when loading the camera point do not match the option selected in the dropdown menu.

The option on the left is the dropdown menu selection, and the option on the right is the actual direction applied when loading:

North: North (correct)
**East: South (Incorrect)
South: East (Incorrect)**
West: West (Correct)

**Comment by NullNameException** [comment]
Sorry about that, I never noticed this. Should be fixed as soon as the new version gets accepted.
