### ISSUE TITLE
Disappeared from Runelite plugins?

### ISSUE THREAD

**Issue by derekmu** [NullNameException/camera-points#7]
I use this plugin all the time, but I just logged in and it's not installed or installable?

The game is practically unplayable for me without this, I'm so used to using keys!

**Comment by derekmu** [comment]
From discord:
```
RuneLite
BOT
 — Today at 6:06 PM
Some hub plugins failed to build against the latest RuneLite version, this means that they're not available until the owner updates them.
```

Can we get this updated?

**Comment by NullNameException** [comment]
Updated it thanks to @KogasaPls
The plugin should work again once the new version gets accepted!

**Comment by derekmu** [comment]
Thanks to both of you!
